#!/bin/bash
# genlogs_apache - Splunk Training
# Generates random virtual apache logs
# Author: Kevin Fajardo
# Contact: kevinfajardosoto12@gmail.com

# VARIABLES
n_server=""
server_name=$(sed "1q;d" ../info | cut -d= -f2)

# FUNCTIONS
random_function() {
        echo $(($RANDOM % $1 + 1))
}

# selects the ip address from the servers list
select_ip_add() {
	echo $(sed "$(($1+1))q;d" ../servers | cut -d: -f1)
}	# $1 sera igual a $i del for function

# format the date
date_format() {
	echo $(date '+%d/%b/%Y:%H:%M:%S %Z')
}

# selects a random endpoints from the list ./endpoints
add_endpoint() {
	n_endpoints=$(wc -l < ./endpoints)
	sed "$(random_function ${n_endpoints})q;d" ./endpoints
}

# MAIN PROGRAM
n_server=$(wc -l < ../servers)

for (( i=0; i<${n_server}; i++)); do
	echo $(select_ip_add ${i})" - - ["$(date_format)"] "$(add_endpoint) >> ../${server_name}$((i+1))/apache.log
done

# DONE / EXIT
exit 0


# Idea
###	192.168.2.20 - - [28/Jul/2022:10:27:10 -0300] "GET /cgi-bin/try/ HTTP/1.0" 200 3395
###	127.0.0.1 - - [28/Jul/2022:10:22:04 -0300] "GET / HTTP/1.0" 200 2216
###	127.0.0.1 - - [28/Jul/2022:10:27:32 -0300] "GET /hidden/ HTTP/1.0" 404 7218
###	10.202.4.90 - - [13/Sep/2022:07:01:53 -0700] "PROPFIND /svn/wsa/Extranet/branches/SOW-101 HTTP/1.1" 404 587
###	10.202.4.85 - - [13/Sep/2022:07:01:51 -0700] "POST /svn/services/connections/trunk HTTP/1.1" 401 587
###	10.202.7.14 - [13/Sep/2022:07:00:53 -0700] "PROPFIND /svn/access/my_custom_app/2.5 HTTP/1.1" 401 587
###	10.202.5.20 - - [13/Sep/2022:07:00:53 -0700] "PROPFIND /svn/wsa/Extranet/branches/SOW-101 HTTP/1.1" 200 587
###	10.202.4.56 - - [13/Sep/2022:07:00:21 -0700] "POST /svn/services/connections/trunk HTTP/1.1" 201 587
###	10.202.10.6 - - [13/Sep/2022:06:59:53 -0700] "PROPFIND /svn/access/my_custom_app/2.5 HTTP/1.1" 200 587
###	10.202.41.4 - - [13/Sep/2022:06:59:50 -0700] "PROPFIND /svn/services/connections/trunk HTTP/1.1" 401 587
###	10.202.0.52 - - [13/Sep/2022:06:58:52 -0700] "POST /svn/services/connections/trunk HTTP/1.1" 401 587
###	10.202.8.8 - - [13/Sep/2022:06:58:52 -0700] "PROPFIND /svn/wsa/Extranet/branches/SOW-101 HTTP/1.1" 401 587
